# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  base_directory: c:/actions-runner/_work/

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  startVM:
    runs-on: ubuntu-latest
    steps: 

    - name: Start AWS EC2
    # Run AWS Command on the GitHub Hosted runner which starts the instance using AWS authentication stored in GitHub Secrets (see below how to add)
      run: |
        aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  pythonCode:
    runs-on: self-hosted
    needs: startVM
    steps:
    
    - name: Generate New SLPS
      working-directory: ${{env.base_directory}}
      run: 
        python ${{env.base_directory}}/PythonLib/ToolsTales_Executable.py --game TOR pack SLPS
          
  closeVM:
    runs-on: ubuntu-latest
    needs: pythonCode
    steps:
    

    - name: Stop AWS EC2
    # Run AWS Command on the GitHub Hosted runner which starts the instance using AWS authentication stored in GitHub Secrets (see below how to add)
      run: |
        aws ec2 stop-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
